---
title: "550Presentation"
author: "Claudia Nikel"
date: "09/12/2019"
output: html_document
---

## Shiny App
```{r}
library(shiny)
source("airports.R")
source("cancellations.R")

server <-function(input,output){ 
  source("airports.R")
  source("cancellations.R")
    output$delayed<- renderPlot({
cutoff<-input$cutoff
par(mar=c(1, 1, 3, 1))
plot(latitude_deg ~ longitude_deg, data = subset(airports,NArrivals>10000), cex=sqrt(NArrivals)/100,ylim=c(21, 50), xlim=c(-125, -65), axes=FALSE, xlab="", ylab="",col="grey")
title("Connections with the most delayed flights")
legend("bottomleft", legend=c("size: No. Flights"), pch=c(1))
legend("bottomright", legend=c("Code size: No. Cancelled Flights")) 
with(subset(cancellations, (DepDelay+ArrDelay)>cutoff), segments(longOrigin, latOrigin, longDest, latDest, col="blue", lwd=sqrt(DepDelay+ArrDelay)/30))
text(latitude_deg ~ longitude_deg, label=iata_code, data = subset(airports, NArrivals>10000), ylim=c(21, 50), xlim=c(-125, -65), cex=sqrt(Cancelled)/70)

    })
    
output$cancelled<- renderPlot({
cutoff<-input$cutoff
par(mar=c(1, 1, 3, 1))
plot(latitude_deg ~ longitude_deg, data = subset(airports,NArrivals>10000), cex=sqrt(NArrivals)/100,ylim=c(21, 50), xlim=c(-125, -65), axes=FALSE, xlab="", ylab="",col="grey")
title("Connections with the most cancelled flights")
legend("bottomleft", legend=c("size: No. Flights"), pch=c(1))
legend("bottomright", legend=c("Code size: No. Cancelled Flights")) 
with(subset(cancellations, Cancelled>cutoff), segments(longOrigin, latOrigin, longDest, latDest, col="red", lwd=Cancelled/500))
text(latitude_deg ~ longitude_deg, label=iata_code, data = subset(airports, NArrivals>10000), ylim=c(21, 50), xlim=c(-125, -65), cex=sqrt(Cancelled)/70)   
    
})   
    
}

ui <- shinyUI(pageWithSidebar(
  headerPanel("What airports and flight connections to avoid?"),
  sidebarPanel(
    #textInput("delay_cutoff", "Enter your delay cutoff parameter:", "800"),
    sliderInput("cutoff", "Cutoff parameter:", min=0, max=750, value=250),
  ),
  mainPanel(
    tabsetPanel(
      tabPanel("Delayed", plotOutput("delayed")), 
      tabPanel("Cancelled", plotOutput("cancelled"))
    
)
)
))
shinyApp(ui=ui, server=server)
```

```{r}
library(shiny)
source("airports.R")
source("cancellations.R")
runApp("flight/")
shinyApp(ui=ui, server=server)
```

## Cancelled Flights Bar Graph
```{r}
library(ggplot2)
library(ggthemr)
top_cancelled_connections<-cancellations[order(cancellations$Cancelled,decreasing=T)[1:5],]
top_cancelled_connections$connections<-row.names(top_cancelled_connections)
top_cancelled_connections

theme_update(plot.title = element_text(hjust = 0.5))
my_graph<-ggplot(top_cancelled_connections, aes(factor(top_cancelled_connections$connections), top_cancelled_connections$Cancelled, fill=factor(top_cancelled_connections$connections))) + geom_bar(stat="identity") + scale_fill_brewer(palette = "Set1")+ggtitle("Amount of Cancelled Flights for Top 5 Worst Connections")+xlab("Airport Codes") + ylab("Cancelled Flights")+scale_fill_manual(values = c("grey", "grey", "grey","red", "lightcoral"))+guides(fill=guide_legend(title="Connections"))+geom_text(aes(label=top_cancelled_connections$Cancelled), vjust=1.6, color="white", size=3.5)
#ggsave("cancelled_flights.pdf")
my_graph
```

## Delayed Flights Bar Graph
```{r}
top_delayed_connections<-cancellations[order(cancellations$ArrDelay+cancellations$DepDelay,decreasing=T)[1:5],]
top_delayed_connections$delays<-top_delayed_connections$ArrDelay+top_delayed_connections$DepDelay
top_delayed_connections$connections<-row.names(top_delayed_connections)



theme_update(plot.title = element_text(hjust = 0.5))
my_graph<-ggplot(top_delayed_connections, aes(factor(top_delayed_connections$connections), top_delayed_connections$delays, fill=factor(top_delayed_connections$connections))) + geom_bar(stat="identity") + scale_fill_brewer(palette = "Set1")+ggtitle("Amount of Delayed Flights for Top 5 Worst Connections")+xlab("Airport Codes") + ylab("Delayed Flights")+scale_fill_manual(values = c("blue", "grey", "grey","cornflowerblue", "grey"))+guides(fill=guide_legend(title="Connections"))+geom_text(aes(label=top_delayed_connections$delays), vjust=1.6, color="white", size=3.5)
#ggsave("delayed_flights.pdf")
my_graph
```


## Cancelled Flights Map 
```{r}
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
library(ggrepel)
top_cancelled_flights<-airports[order(airports$Cancelled,decreasing=T)[1:5],]
top_cancelled_connections$start<-c("LGA","ORD","","","DCA")
top_cancelled_connections$end<-c("","","","BOS","")


usa<-map_data("usa")
gg1<-ggplot() + geom_polygon(data = usa, aes(x=long, y = lat, group = group),fill = "grey") + coord_fixed(1.3)

gg1+geom_segment(data=top_cancelled_connections,aes(x=longOrigin, y=latOrigin, xend=longDest, yend=latDest),colour="red",alpha=0.5)+geom_point(data = top_cancelled_connections, aes(x=longOrigin, y=latOrigin), color = "white", size = 4)+geom_point(data=top_cancelled_connections, aes(x=longOrigin, y=latOrigin), color = "red", size = 3)+geom_point(data=top_cancelled_connections, aes(x=longDest, y=latDest), color = "white", size = 4)+geom_point(data=top_cancelled_connections, aes(x=longDest, y=latDest), color = "red", size = 3)+ggtitle("Map of 5 Worst Cancelled Flight Connections ")+ylab("Latitude")+xlab("Longitude")+geom_text_repel(data=top_cancelled_connections, aes(label=start,x=longOrigin, y=latOrigin))+geom_text_repel(data=top_cancelled_connections, aes(label=end,x=longDest, y=latDest))
#ggsave("cancelled_flights_map.pdf")
```


## Delayed Flights Map
```{r}
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
library(ggrepel)

top_delayed_connections$start<-c("AUS","MCI","BWI","PBI","BHM")
top_delayed_connections$end<-c("ELP","BNA","PIT","BWI","BWI")
top_delayed_connections[5, 15] = ""


usa<-map_data("usa")
gg1<-ggplot() + geom_polygon(data = usa, aes(x=long, y = lat, group = group),fill = "grey") + coord_fixed(1.3)

gg1+geom_segment(data=top_delayed_connections,aes(x=longOrigin, y=latOrigin, xend=longDest, yend=latDest),colour="blue",alpha=0.5)+geom_point(data = top_delayed_connections, aes(x=longOrigin, y=latOrigin), color = "white", size = 4)+geom_point(data=top_delayed_connections, aes(x=longOrigin, y=latOrigin), color = "blue", size = 3)+geom_point(data = top_delayed_connections, aes(x=longDest, y=latDest), color = "white", size = 4)+geom_point(data=top_delayed_connections, aes(x=longDest, y=latDest), color = "blue", size = 3)+ggtitle("Map of 5 Worst Delayed Flight Connections ")+ylab("Latitude")+xlab("Longitude")+geom_text_repel(data=top_delayed_connections, aes(label=start,x=longOrigin, y=latOrigin))+geom_text_repel(data=top_delayed_connections, aes(label=end,x=longDest, y=latDest))
#ggsave("delayed_flights_map.pdf")
```